//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expelled_students
    {
        public int IDStudent { get; set; }
        public string FullName { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<System.DateTime> DropDate { get; set; }
    }
}
