//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPA
    {
        public int ID_GPA { get; set; }
        public Nullable<int> ID_Студента { get; set; }
        public Nullable<double> gpa1 { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
