//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int ID_Оценки { get; set; }
        public Nullable<int> ID_Дисциплины { get; set; }
        public Nullable<int> Семестр { get; set; }
        public Nullable<int> ID_Студента { get; set; }
        public Nullable<System.DateTime> Дата_сдачи { get; set; }
        public Nullable<double> Оценка { get; set; }
    
        public virtual Dist Dist { get; set; }
        public virtual Students Students { get; set; }
    }
}
