//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUP
    {
        public int ID_RUP { get; set; }
        public Nullable<int> ID_Дисциплины { get; set; }
        public Nullable<int> ID_Специальности { get; set; }
        public Nullable<int> ID_Категории { get; set; }
        public Nullable<int> ID_Преподавателя { get; set; }
        public Nullable<int> семестр { get; set; }
        public string вид_аттестации { get; set; }
        public Nullable<int> Количество_часов { get; set; }
    
        public virtual Dist Dist { get; set; }
        public virtual Kat Kat { get; set; }
        public virtual Spec Spec { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
